<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Поиск");
?>

<?$APPLICATION->IncludeComponent(
    "consult-info:search.page",
    ".default",
    array(
        "TAGS_SORT" => "NAME",
        "TAGS_PAGE_ELEMENTS" => "150",
        "TAGS_PERIOD" => "30",
        "TAGS_URL_SEARCH" => "/search/index.php",
        "TAGS_INHERIT" => "N",
        "FONT_MAX" => "50",
        "FONT_MIN" => "10",
        "COLOR_NEW" => "000000",
        "COLOR_OLD" => "C8C8C8",
        "PERIOD_NEW_TAGS" => "",
        "SHOW_CHAIN" => "Y",
        "COLOR_TYPE" => "Y",
        "WIDTH" => "100%",
        "USE_SUGGEST" => "N",
        "SHOW_RATING" => "Y",
        "PATH_TO_USER_PROFILE" => "",
        "AJAX_MODE" => "N",
        "RESTART" => "Y",
        "NO_WORD_LOGIC" => "N",
        "USE_LANGUAGE_GUESS" => "Y",
        "CHECK_DATES" => "Y",
        "USE_TITLE_RANK" => "Y",
        "DEFAULT_SORT" => "rank",
        "FILTER_NAME" => "",
        "arrFILTER" => array(),
        "SHOW_WHERE" => "Y",
        "arrWHERE" => array(),
        "arrFILTER_iblock_public" => array(),
        "arrFILTERext" => array(
            0 => "iblock_news",
            1 => "iblock_subjects",
            2 => "iblock_documents",
            4 => "main",
        ),
        "arrFILTERext_iblock_public" => array(
            0 => "18",
            1 => "21",
            2 => "24",
            3 => "11",
            4 => "14",
            5 => "15",
            6 => "16",
            7 => "9",
        ),
        "SHOW_WHEN" => "N",
        "PAGE_RESULT_COUNT" => "4",
        "IBLOCK_TYPE_SEARCH" => "public",
        "CACHE_TYPE" => "N",
        "CACHE_TIME" => "3600",
        "DISPLAY_TOP_PAGER" => "Y",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "PAGER_TITLE" => "Результаты поиска",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => "mm_pagination",
        "AJAX_OPTION_SHADOW" => "Y",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "COMPONENT_TEMPLATE" => ".default",
        "SHOW_ITEM_TAGS" => "Y",
        "SHOW_ITEM_DATE_CHANGE" => "Y",
        "SHOW_ORDER_BY" => "Y",
        "SHOW_TAGS_CLOUD" => "N",
        "arrFILTER_main" => array(
        ),
        "STRUCTURE_FILTER" => "structure",
        "NAME_TEMPLATE" => "",
        "SHOW_LOGIN" => "Y"
    ),
    false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>